EventHub/Entities/Event.cs
using System.ComponentModel.DataAnnotations;

namespace EventHub.Entities
{
    public class Event
    {
        public int Id { get; set; }

        [Required]
        [StringLength(200, MinimumLength = 2)]
        [Display(Name = "Title")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Image Path")]
        public string ImagePath { get; set; }


        [Required]
        public string Description { get; set; }

        [Display(Name = "HTML Content")]
        public string HTMLContent { get; set; }

        [Display(Name = "Added At")]
        public DateTime Added { get; set; }

        [Display(Name = "Categories")]
        public int CategoryId { get; set; }

        public List<UserEvent> UserEvents { get; set; } = new List<UserEvent>();

    }
}

EventHub/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EventHub.Data;
using EventHub.Entities;
using Microsoft.AspNetCore.Authorization;
using System.Data.SqlTypes;

namespace EventHub.Controllers
{
    
    public class EventsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EventsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Events
        [Authorize(Roles = ("Admin"))]
        public async Task<IActionResult> Index(int categoryId)
        {
            if(categoryId == 0)
            {
                return View(await _context.Events.ToListAsync());
            }
            else
            {
                List<Event> list = await (from e in _context.Events
                                          where e.CategoryId == categoryId
                                          select new Event
                                          {
                                              Id = e.Id,
                                              Name = e.Name,
                                              ImagePath = e.ImagePath,
                                              Description = e.Description,
                                              HTMLContent = e.HTMLContent,
                                              Added = e.Added,
                                              CategoryId = categoryId
                                          }).ToListAsync();

                ViewBag.CategoryId = categoryId;
                return View(list);

            }
            
        }

        // GET: Events/Details/5
        [Authorize(Roles = ("Admin"))]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Events/Create
        [Authorize(Roles = ("Admin"))]
        public IActionResult Create(int categoryId)
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            Event @event = new Event
            {
                CategoryId = categoryId,
                Added = DateTime.Now

            };
            return View(@event);

        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        [Authorize(Roles = ("Admin"))]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,ImagePath,Description,HTMLContent,Added,CategoryId")] Event @event)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { categoryId = @event.CategoryId });
            }
            return View(@event);
        }

        // GET: Events/Edit/5
        [Authorize(Roles = ("Admin"))]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        [Authorize(Roles = ("Admin"))]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,ImagePath,Description,HTMLContent,Added,CategoryId")] Event @event)
        {
            if (id != @event.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { categoryId = @event.CategoryId });
            }
            return View(@event);
        }

        // GET: Events/Delete/5
        [Authorize(Roles = ("Admin"))]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Events/Delete/5
        [Authorize(Roles = ("Admin"))]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @event = await _context.Events.FindAsync(id);
            if (@event != null)
            {
                _context.Events.Remove(@event);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { categoryId = @event.CategoryId });
        }



        //Get all events
        [HttpGet]
        public async Task<IActionResult> AllEvents(int categoryId)
        {
            if (categoryId == 0)
            {
                return View(await _context.Events.ToListAsync());
            }
            else
            {
                List<Event> list = await (from e in _context.Events
                                          where e.CategoryId == categoryId
                                          select new Event
                                          {
                                              Id = e.Id,
                                              Name = e.Name,
                                              ImagePath = e.ImagePath,
                                              Description = e.Description,
                                              HTMLContent = e.HTMLContent,
                                              Added = e.Added,
                                              CategoryId = categoryId
                                          }).ToListAsync();

                ViewBag.CategoryId = categoryId;
                return View(list);

            }

        }


        // GET: Event Detail
        [HttpGet]
        public async Task<IActionResult> EventDetail(int id)
        {
            var eventDetails = await _context.Events.FindAsync(id);

            if (eventDetails == null)
            {
                return NotFound();
            }

            return PartialView("_EventDetailPartial", eventDetails);
        }




        private bool EventExists(int id)
        {
            return _context.Events.Any(e => e.Id == id);
        }
    }
}

EventHub/Controllers/UserEventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EventHub.Data;
using EventHub.Entities;
using Microsoft.AspNetCore.Identity;

namespace EventHub.Controllers
{
    public class UserEventsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        public UserEventsController(ApplicationDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: UserEvents
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.UserEvents.Include(u => u.Event).Include(u => u.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: UserEvents/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userEvent = await _context.UserEvents
                .Include(u => u.Event)
                .Include(u => u.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userEvent == null)
            {
                return NotFound();
            }

            return View(userEvent);
        }

        // GET: UserEvents/Create
        public IActionResult Create(int eventId)
        {
            ViewData["EventId"] = new SelectList(_context.Events, "Id", "Description", eventId);
            return View();
        }

        // POST: UserEvents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,EventId,Event,AppUser")] UserEvent userEvent)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userEvent);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventId"] = new SelectList(_context.Events, "Id", "Description", userEvent.EventId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", userEvent.UserId);
            return View(userEvent);
        }

        // GET: UserEvents/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userEvent = await _context.UserEvents.FindAsync(id);
            if (userEvent == null)
            {
                return NotFound();
            }
            ViewData["EventId"] = new SelectList(_context.Events, "Id", "Description", userEvent.EventId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", userEvent.UserId);
            return View(userEvent);
        }

        // POST: UserEvents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,EventId")] UserEvent userEvent)
        {
            if (id != userEvent.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userEvent);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserEventExists(userEvent.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventId"] = new SelectList(_context.Events, "Id", "Description", userEvent.EventId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", userEvent.UserId);
            return View(userEvent);
        }

        // GET: UserEvents/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userEvent = await _context.UserEvents
                .Include(u => u.Event)
                .Include(u => u.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userEvent == null)
            {
                return NotFound();
            }

            return View(userEvent);
        }

        //POST: UserEvents/Delete/5/ By The Admin
        //To redirect the admin to the index page of all events
        [HttpPost, ActionName("DeleteAdmin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmedAdmin(int id)
        {
            var userEvent = await _context.UserEvents.FindAsync(id);
            if (userEvent != null)
            {
                _context.UserEvents.Remove(userEvent);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //Handle the user registration for an event.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignInForEvent(int eventId)
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return Unauthorized();
            }

            var userEvent = new UserEvent
            {
                UserId = user.Id,
                EventId = eventId
            };

            _context.UserEvents.Add(userEvent);
            await _context.SaveChangesAsync();

            return RedirectToAction("MyEvents"); // Redirect to MyEvents view
        }


        // GET: UserEvents/MyEvents
        public async Task<IActionResult> MyEvents()
        {
            var user = await _userManager.GetUserAsync(User);
            var userEvents = await _context.UserEvents
                                           .Include(ue => ue.Event)
                                           .Where(ue => ue.UserId == user.Id)
                                           .ToListAsync();
            return View(userEvents);
        }

        //POST: UserEvents/Delete/5/By The User 
        //To redirect the user to his events
        [HttpPost, ActionName("DeleteUser")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmedUser(int id)
        {
            var userEvent = await _context.UserEvents.FindAsync(id);
            if (userEvent != null)
            {
                _context.UserEvents.Remove(userEvent);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(MyEvents));
        }



        private bool UserEventExists(int id)
        {
            return _context.UserEvents.Any(e => e.Id == id);
        }
    }
}

EventHub/Views/Events/AllEvents.cshtml
@using EventHub.Entities
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer ViewLocalizer
@model IEnumerable<Event>

@{
    ViewData["Title"] = "All Events";
}

@if (!Model.Any())
{
    <div class="container">
        <p>There are no events found for this category.</p>
    </div>
}
else
{
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                    <div class="card border-primary h-100">
                        <img src="@item.ImagePath" class="card-img-top" alt="@item.Name">
                        <div class="card-body">
                            <h5 class="card-title">@item.Name</h5>
                            <p class="card-text">@item.Description</p>
                            <button type="button" class="btn btn-primary see-more" data-id="@item.Id" data-bs-toggle="modal" data-bs-target="#eventModal">
                                @ViewLocalizer["See More"]
                            </button>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">Added on @item.Added.ToString("MMMM dd, yyyy")</small>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="eventModal" tabindex="-1" aria-labelledby="eventModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="eventModalLabel">Modal title</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <!-- Dynamic content will be loaded here -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">@ViewLocalizer["Close"]</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>

    @section Scripts {
    <script>
        $(document).ready(function () {
            $('.see-more').click(function () {
                var eventId = $(this).data('id');
                $.ajax({
                    url: '@Url.Action("EventDetail", "Events")',
                    data: { id: eventId },
                    success: function (data) {
                        $('#eventModal .modal-content').html(data);
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        console.error('Error:', textStatus, errorThrown);
                    }
                });
            });
        });
    </script>
    }
}

EventHub/Views/Events/Create.cshtml
@model EventHub.Entities.Event

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId">
                    <option value="">--Please Select a Category--</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" rows="2" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HTMLContent" class="control-label"></label>
                <textarea asp-for="HTMLContent" rows="10" class="form-control"></textarea>
                <span asp-validation-for="HTMLContent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Added" class="control-label"></label>
                <input asp-for="Added" class="form-control" />
                <span asp-validation-for="Added" class="text-danger"></span>
            </div><br />
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />

<div>
    <a asp-action="Index" asp-route-categoryId="@Model.CategoryId" class="btn btn-secondary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EventHub/Views/Events/Delete.cshtml
@model EventHub.Entities.Event

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HTMLContent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HTMLContent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Added)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Added)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <a asp-action="Index" asp-route-categoryId="@Model.CategoryId" class="btn btn-secondary">Back to List</a>
    </form>
</div>

EventHub/Views/Events/Details.cshtml
@model EventHub.Entities.Event

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Event</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HTMLContent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HTMLContent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Added)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Added)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-info">Edit</a> 
    <a asp-action="Index" asp-route-categoryId="@Model.CategoryId" class="btn btn-secondary">Back to List</a>
</div>

EventHub/Views/Events/Edit.cshtml
@model EventHub.Entities.Event

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Edit">
            <input type="hidden" asp-for="CategoryId" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" rows="2" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HTMLContent" class="control-label"></label>
                <textarea asp-for="HTMLContent" rows="10" class="form-control"></textarea>
                <span asp-validation-for="HTMLContent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Added" class="control-label"></label>
                <input asp-for="Added" class="form-control" />
                <span asp-validation-for="Added" class="text-danger"></span>
            </div><br />
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div><br />

<div>
    <a asp-action="Index" asp-route-categoryId="@Model.CategoryId" class="btn btn-secondary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EventHub/Views/Events/Index.cshtml
@using System.Globalization
@using EventHub.Entities
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer ViewLocalizer
@model IEnumerable<EventHub.Entities.Event>

@{
    ViewData["Title"] = "Index";
}

<h1>@ViewLocalizer["All Events"]</h1>

<p>
    <a asp-action="Create" asp-route-categoryId="@ViewBag.CategoryId" class="btn btn-primary">@ViewLocalizer["Create New"]</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImagePath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.Added)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImagePath)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.Added)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="text-info mr-2"><i class="fas fa-edit"></i></a>
                <a asp-action="Details" asp-route-id="@item.Id" class="text-dark mr-2"><i class="fas fa-table"></i></a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="text-danger mr-2"><i class="fas fa-trash"></i></a>
            </td>
        </tr>
}
    </tbody>
</table>

EventHub/Views/Events/_EventDetailPartial.cshtml
@model EventHub.Entities.Event
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Antiforgery

@{
    ViewData["Title"] = "Event Detail";
    var requestToken = Antiforgery.GetAndStoreTokens(Context).RequestToken;
}

<div class="modal-header">
    <h5 class="modal-title">@Model.Name</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
    @Html.Raw(Model.HTMLContent)
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    @if (User.Identity.IsAuthenticated)
    {
        <form method="post" action="@Url.Action("SignInForEvent", "UserEvents")">
            @Html.AntiForgeryToken()
            <input type="hidden" name="eventId" value="@Model.Id" />
            <button type="submit" class="btn btn-primary">Sign In</button>
        </form>
    }
    else
    {
        <a class="btn btn-primary" href="/Identity/Account/Register">Sign Up to Sign In</a>
    }
</div>