EventHub/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EventHub.Data;
using EventHub.Entities;
using Microsoft.AspNetCore.Authorization;

namespace EventHub.Controllers
{
    [Authorize(Roles = ("Admin"))]
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index(string searchString)
        {
            var categories = from category in _context.Categories
                             select category;

            if(!String.IsNullOrEmpty(searchString))
            {
                categories = categories.Where(s => s.Name.Contains(searchString));
                return View(categories);
            }

            return View(await _context.Categories.ToListAsync());


         }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .Include(c => c.Events)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,ImagePath")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,ImagePath")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.Id == id);
        }
    }
}

EventHub/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EventHub.Data;
using EventHub.Entities;
using Microsoft.AspNetCore.Authorization;
using System.Data.SqlTypes;

namespace EventHub.Controllers
{
    
    public class EventsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EventsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Events
        [Authorize(Roles = ("Admin"))]
        public async Task<IActionResult> Index(int categoryId)
        {
            if(categoryId == 0)
            {
                return View(await _context.Events.ToListAsync());
            }
            else
            {
                List<Event> list = await (from e in _context.Events
                                          where e.CategoryId == categoryId
                                          select new Event
                                          {
                                              Id = e.Id,
                                              Name = e.Name,
                                              ImagePath = e.ImagePath,
                                              Description = e.Description,
                                              HTMLContent = e.HTMLContent,
                                              Added = e.Added,
                                              CategoryId = categoryId
                                          }).ToListAsync();

                ViewBag.CategoryId = categoryId;
                return View(list);

            }
            
        }

        // GET: Events/Details/5
        [Authorize(Roles = ("Admin"))]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Events/Create
        [Authorize(Roles = ("Admin"))]
        public IActionResult Create(int categoryId)
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            Event @event = new Event
            {
                CategoryId = categoryId,
                Added = DateTime.Now

            };
            return View(@event);

        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        [Authorize(Roles = ("Admin"))]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,ImagePath,Description,HTMLContent,Added,CategoryId")] Event @event)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { categoryId = @event.CategoryId });
            }
            return View(@event);
        }

        // GET: Events/Edit/5
        [Authorize(Roles = ("Admin"))]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        [Authorize(Roles = ("Admin"))]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,ImagePath,Description,HTMLContent,Added,CategoryId")] Event @event)
        {
            if (id != @event.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { categoryId = @event.CategoryId });
            }
            return View(@event);
        }

        // GET: Events/Delete/5
        [Authorize(Roles = ("Admin"))]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Events/Delete/5
        [Authorize(Roles = ("Admin"))]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @event = await _context.Events.FindAsync(id);
            if (@event != null)
            {
                _context.Events.Remove(@event);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { categoryId = @event.CategoryId });
        }



        //Get all events
        [HttpGet]
        public async Task<IActionResult> AllEvents(int categoryId)
        {
            if (categoryId == 0)
            {
                return View(await _context.Events.ToListAsync());
            }
            else
            {
                List<Event> list = await (from e in _context.Events
                                          where e.CategoryId == categoryId
                                          select new Event
                                          {
                                              Id = e.Id,
                                              Name = e.Name,
                                              ImagePath = e.ImagePath,
                                              Description = e.Description,
                                              HTMLContent = e.HTMLContent,
                                              Added = e.Added,
                                              CategoryId = categoryId
                                          }).ToListAsync();

                ViewBag.CategoryId = categoryId;
                return View(list);

            }

        }


        // GET: Event Detail
        [HttpGet]
        public async Task<IActionResult> EventDetail(int id)
        {
            var eventDetails = await _context.Events.FindAsync(id);

            if (eventDetails == null)
            {
                return NotFound();
            }

            return PartialView("_EventDetailPartial", eventDetails);
        }




        private bool EventExists(int id)
        {
            return _context.Events.Any(e => e.Id == id);
        }
    }
}

EventHub/Views/Shared/_AdminMenuPartial.cshtml
@using EventHub.Data
@using Microsoft.AspNetCore.Identity
@using System.Globalization
@using EventHub.Entities
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer ViewLocalizer
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager


 @if (User.IsInRole("Admin"))
    {
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-dark" href="#" data-bs-toggle="dropdown">Admin</a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" asp-controller="Categories" asp-action="Index">Event Categories</a></li>
                <li><a class="dropdown-item" asp-controller="Events" asp-action="Index">Events</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" asp-controller="UserEvents" asp-action="Index">User to Event</a></li>
            </ul>
        </li>
    }

EventHub/Views/Shared/_Layout.cshtml
@using EventHub.Data
@using Microsoft.AspNetCore.Identity
@using System.Globalization
@using EventHub.Entities
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer ViewLocalizer
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EventHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EventHub.styles.css" asp-append-version="true" />
    <link href="~/fontawesome/css/all.min.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EventHub</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@ViewLocalizer["Home"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="AllEvents">@ViewLocalizer["All Event"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/#ContactUs">@ViewLocalizer["Contact Us"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/#AboutUs">@ViewLocalizer["About Us"]</a>
                        </li>

                        <partial name="_AdminMenuPartial" />
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserEvents" asp-action="MyEvents">@ViewLocalizer["My Events"]</a>
                            </li>
                        }
                        
                            
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <partial name="_SetLanguagePartial" />
                        </li>
                        <li class="nav-item">
                            <partial name="_LoginPartial" />
                        </li>
                    </ul>
            </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EventHub - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EventHub/Views/Shared/_SetLanguagePartial.cshtml
@using Microsoft.AspNetCore.Localization;
@using Microsoft.AspNetCore.Mvc.Localization;
@using Microsoft.Extensions.Options
@inject IViewLocalizer ViewLocalizer;
@inject IOptions<RequestLocalizationOptions> LocOptions;
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures.Select(x => new SelectListItem { Value = x.Name, Text = x.DisplayName }).ToList();
}








<form class="d-flex" asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path" method="post">
    <label class="form-label me-2" for="languageSelect">Languages:</label>
    <select id="languageSelect" name="culture" asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems" class="form-control form-control-sm" onchange="this.form.submit();"></select>
</form>